### ISSUE TITLE
LoRa Messaging not working

### ISSUE THREAD

**Issue by FunkyCold-DC940** [ESP32-WiPhone/wiphone-firmware#35]
Just received two phones, installed the LoRa daughter boards. Attempted to send messages between the two phones and neither is receiving the test messages. I have tried removing and and reinstalling in case something was not properly making contact. Still not able to receive messages between the two phones.

**Comment by FunkyCold-DC940** [comment]
removed and re-added the contacts I had created and all seems to be working now.

**Comment by nosliwneb** [comment]
We have a firmware release in the works that has a lot of improvements in
this area. Retries, confirmation of receipt, etc.

Message ID: <ESP32-WiPhone/wiphone-firmware/issue/35/issue_event/9041342083@
github.c
